name: 'Send mail'

on:
  # push:
  schedule:
    - cron: '0 1 * * *'

jobs:
  send:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: 'Get Date'
        run: echo "REPORT_DATE==$(TZ=':Pacific/Samoa' date '+%Y-%m-%d %T')"  >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Today's events" --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CURRENT_EVENTS_TOKEN }}
      - name: AWS Profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: mail
          region: us-west-1
          key: ${{ secrets.AWS_KEY }}
          secret: ${{ secrets.AWS_SECRET }}
      - name: Send mail
        run: AWS_PROFILE=mail npm run send
        env: 
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }} 
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }} 
